name: center
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0 
  http: ^0.13.5 
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.3.1
  get: ^4.6.5
  cupertino_icons: ^1.0.8
  fl_country_code_picker: ^0.1.9+1
  image_picker: ^0.8.4+8  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_maps_flutter: ^2.2.0 

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/home.png
